### PR TITLE
Fix for date x axis

### PR DESCRIPTION
**Pull request by hakantkn**
Added xIsDate and dateFormat for date x values.
Added a new example using date data label
Also added labelTemplate and a new addData method using this template.

#106 Fixes date label issue

### CODE REVIEW

**Comment by timmolter** [comment]
In `AxisTickCalculator_Date`  a pattern is automatically dtermined. 

    String datePattern = timeSpans.get(index).getDatePattern();

Later it could be overridden by this:

      if (styler.getDatePattern() != null) {
        datePattern = styler.getDatePattern();
      }

Could you make the data labeller uses this instead of having a separate formatter?

**Comment by hakantkn** [comment]
Can I assume styler is always AxesChartStyler?

**Comment by timmolter** [comment]
I think so.

**Comment by hakantkn** [comment]
This way it uses AxisTickCalculator_Date's format & automatically sets x to date

**Comment by timmolter** [comment]
I'll get back to you later on this....

**Comment by timmolter** [comment]
I ended up coding it completely differently.

**Comment by timmolter** [comment]
See latest commit if interested.

**Comment by hakantkn** [comment]
Label generation is cleaner this way.
Here are some comments:
- since you use dataLabeller in PlotContent_.java you don't need null check (`if (chart.dataLabeller != null)`) in PlotContent_* 
- you can move  chart.dataLabeller.paint(g); from PlotContent_* to  PlotContent_.java:
`chart.dataLabeller.startPaint(g);`
`doPaint(g);`
`chart.dataLabeller.paint(g);`

**Comment by timmolter** [comment]
Good cal. updated.

**Comment by fcecchin** [comment]
Is possible to rotate 90º the data annotations?

**Comment by timmolter** [comment]
@fcecchin No, sorry.

**Pull request closed without merging**
