### PR TITLE
Feature: Optional sum (total value) in pie charts

### PR DESCRIPTION
**Pull request by ekleinod**
I implemented my feature request for an optional sum (total value) in pie charts (issue #174)

Additionally I included the test class for VectorGraphicsEncoder, I did not know how to exclude the specific commit.

### CODE REVIEW

**Comment by timmolter** [comment]
Very nice. Can we eliminate the font property and just have it be the same font as `getAnnotationFont()` in the Theme?

**Comment by ekleinod** [comment]
Of course we can do that (it's your project :)).

My reason was that it is more convenient for the eye if the sum is slightly larger than the annotation font. Thus I implemented the sum font.

**Comment by ekleinod** [comment]
But there is another issue, maybe it solves this problem: I realized there is no abstract styler class, thus every change in the styler interface leads to changes in all styles.

If it was ok for you, I would implement an abstract styler class in a way, that all fonts are using the same font or are deriving from it and all implementing classes can but are not required to overwrite these methods.

This way, the sum font would be no problem, it would be the same as the annotation font until someone says otherwise and the introduction of the sum font would require no changes in the styler classes.

I think I could implement this in the evening, maybe tomorrow so you could see if this fits your needs.

**Comment by ekleinod** [comment]
D'oh, one correction from my side: I mean "themes" not "styles". So I would introduce an abstract class `AbstractTheme` or `BaseTheme` implementing the `Theme` interface. All custom themes could derive from this class.

**Comment by timmolter** [comment]
Ah, so you wanted it for the size. OK, let's add a size attribute then. In XChart I've consistently separated Size and Font "Style" although at the Java implementation level it's the combined `Font` class. 

So there'd be a `BaseTheme` and all themes would extend it, and then ,whatever needs to be changed from the default is overridden?

**Comment by ekleinod** [comment]
I don't see any font size attributes or methods neither in `Styler` nor `Theme`. Could you give me a hint, so I don't destroy your conventions?

As for the `BaseTheme`: yes, this is what I would suggest.

**Comment by ekleinod** [comment]
If it's ok for you I am implementing an example for the abstract base theme for discussion?

**Comment by timmolter** [comment]
Whoops, looks like I mis-remembered things. Your implementation is fine how it stands then. Although size would be easier, so the end user doesn't have think about Fonts. Just use the same font "style" and update the size perhaps. I'll accept whatever you decide.

**Comment by timmolter** [comment]
Yes, please implement the base class.

**Comment by ekleinod** [comment]
I implemented the base class functionality and made some more changes:

- new class `AbstractBaseTheme`
- accordingly new classes `BaseSeriesColors`, `BaseSeriesLines`, `BaseSeriesMarkers`

I updates all theme classes accordingly. They only need to overwrite different values now.

- introducing base font concept for Theme

I introduced a method `getBaseFont` which is used to derive all fonts from. This way you can change all used fonts with one `overwrite`. You still can change all fonts separately. I used the demo for `MyCustomTheme` to show how it is used.

- new method for setting sum size in pie charts `setSumFontSize`

This was as of your request, I still left the method `setSumFont` in the class, mostly for symmetry reasons with the other fonts.

**Comment by timmolter** [comment]
Thanks, really great!

**Comment by ekleinod** [comment]
Thanks.

**Pull request merged**
