### PR TITLE
Improved class Histogram

### PR DESCRIPTION
**Pull request by hwaipy**
Hey,

First time for me to call a pull request on your project.
XChart is really a wonderful solution for drawing diagrams in Java. I really like it, learning to use it and want it to be better.
I'm just beginning to learning your code. Then I noticed a little BUG in class Histogram when creating bins. In line 99, when bin==numBins, the value is on the next bin of the max one, not right one the edge of the max one. If you create a Histogram like this

        Histogram histogram = new Histogram(Arrays.asList(1, 2, 3, 4, 5, 6), 2, 0, 4);

You me get a BarChart like 
qq20150304-1
which is definitely not we expected.

Additionally, I improved the constructor to avoid some performance issue.

List of changes:
1. Improved the constructor. Now it has better performance when the size of data is
vary large (e.g. >1M).
2. Fixed line 99. When bin==numBins, the value falls on the next bin of
the max bin, not right on the edge.

### CODE REVIEW

**Comment by timmolter** [comment]
Thanks for the improvements! I found another little bug in the Histogram code and fixed it as well. I also made a unit test for your example.

**Comment by hwaipy** [comment]
Wonderful!

However, I still fell uncertain on this issue. Should the date falls exactly on the max value be contained?
Suppose a Histogram with N bins. There are (N+1) egdes denoting E_0, E_1, ..., E_N. The kth (k=0, 1, 2, ..., N-1) bin would contains values from E_k (including) to E_k+1 (excluding), which can be expressed as [ E_k, E_k+1 ) in math. So to be fair between bins, the max value should be excluded. 

How do you think?

**Comment by hwaipy** [comment]
I'm sorry this issue is becoming confusing, because I've posted a wrong figure yesterday.

I was trying to say, this
qq20150304-1, instead of this
qq20150304-2, is what we expected.

Since when we create a Histogram by 

    Histogram histogram = new Histogram(Arrays.asList(1, 2, 3, 4, 5, 6), 2, 0, 4);

we created two bins, [0,2) and [2,4) separately. Thus, "1" should be in the first bin, "2" and "3" should be in the second bin, and "4","5","6" should be discarded.

In your old code, both "4" and "5" would be contained in the second bin, which is definitely wrong.
In my code, both "4" and "5" would be discarded.
In your new code, "4" would be contained in the second bin.

So, how do you think? Should the second bin be [2,4) or [2,4]?

**Comment by timmolter** [comment]
I'm happy to discuss this with you.

I'll tell you why I would INCLUDE the MAX. If we use the other constructor:

    public Histogram(Collection<? extends Number> data, int numBins)

the min and max are calculated for us. If the collection contained 100 numbers and 10 were the max value, then the histogram would only include 90 counts using your proposed logic, whereas one would normally want ALL of the values to be accounted for. Therefore, the min and max should be INCLUDED in the leftmost and rightmost bins respectively.

That was my reasoning anyway. If you give it 100 data points, all 100 should make it into the histogram.  If you then manually set the min and max, it should behave the same way (and also share the same code).

Are you OK with that?

**Comment by hwaipy** [comment]
Yes you are right! Thank your for the response.

**Pull request merged**
