### PR TITLE
Added setYAxisMax/setYAxisMin for y axis groups

### PR DESCRIPTION
**Pull request by hakantkn**
Added new methods to AxesChartStyler to handle custom max/min settings for y axis groups:
- `setYAxisMax(Double yAxisMax, Integer yAxisGroup)`
- `setYAxisMin(Double yAxisMax, Integer yAxisGroup)`
- `getYAxisMax(Integer yAxisGroup)`
- `getYAxisMin(Integer yAxisGroup)`

This solves issue #244 

See screenshot below (TestForIssue244.java):
image

### CODE REVIEW

**Comment by waltwj** [comment]
This looks good, but I would change this to match the ordering of parameters in other methods like setAxisGroupTitle(Integer group, String title)

setYAxisMax(Integer yAxisGroup, Double yAxisMax)
setYAxisMin(Integer yAxisGroup, Double yAxisMax)

**Comment by hakantkn** [comment]
I couldn't see the changes but I swapped the parameter ordering

**Comment by waltwj** [comment]
Yeah, it's because I'm such a newbie. How do I get your changes?

**Comment by hakantkn** [comment]
Either fork from my repository or wait @timmolter to merge these changes.

**Comment by waltwj** [comment]
Ok, got it. Thanks. After using it, the only change I'd make now is having the single parameter version only affect group 0. Having it limit all y axes, I believe, negates the reason for having an additional y axis.

**Pull request merged**
