### PR TITLE
Added data labels

### PR DESCRIPTION
**Pull request by hakantkn**
Added data labels.
Added a new class to handle data labels: DataLabeller
Added a MouseMotionListener in XChartPanel class to catch mouse move
events to show pop up data labels.
Added required lines to PlotContent_* to show data labels.
Added a demo for showing various configuration examples:
DataLabellerExample

This resolves issue 106: Support Data labels 
My bitcoin address is 1MNP7rUewVmkEiZfyDaiEJAeBu3egUJw5R

### CODE REVIEW

**Comment by hakantkn** [comment]
This resolves issue #106 : Support Data labels

**Comment by timmolter** [comment]
Payment sent. Thanks!

**Comment by hakantkn** [comment]
Is there any changes needed?

**Comment by timmolter** [comment]
Nope, looks good at first glance.

**Comment by hakantkn** [comment]
Only issue I encountered is on example BarChart06. You cannot select histogram2 values since histogram 1 values are bigger and inserted before histogram 2.

**Comment by timmolter** [comment]
Well, I guess that's ok.

**Comment by timmolter** [comment]
The date charts should show the formatted values, not the epoch long values on the labels

**Comment by hakantkn** [comment]
Instead of using an enum to create labels, a string template can be used to create labels.
But this requires the argument to be casted to long (to format it as date/time).

Another alternative is to add another addData method:
Eg:
  public void addData(Shape shape, double xOffset, double yOffset, double width, Object... params) {
    String.format(labelTemplate, params);
    DataPoint dp = new DataPoint(shape, xOffset, yOffset, width, label);
    dataPointList.add(dp);
  }

**Comment by hakantkn** [comment]
Created a new pull request #183

**Pull request merged**
