### PR TITLE
Added multiple Y axes feature.

### PR DESCRIPTION
**Pull request by hakantkn**
Added multiple y axes feature.
See TestForIssue54.java.

This resolves issue #54 
My bitcoin address is 15V12VPCWmAupBkwfvZtn8L2rHrhCHE37x

### CODE REVIEW

**Comment by hakantkn** [comment]
Added y axis right/left alignment.
This resolves issue #130

**Comment by hakantkn** [comment]
Added InsideS & OutsideS legend position options this resolves #149

**Comment by timmolter** [comment]
Good job so far. Here are 4 mistakes that I see:
screen shot 2017-05-26 at 10 22 39 am

**Comment by hakantkn** [comment]
I'll work on these issues.

**Comment by hakantkn** [comment]
I fixed 2 of the problems:
- gap between axis tick and plot
- x axis shifted right

> They are not both on the second axis

- b = a*2
- d ~= b*2 + 1
- a & c uses first axis on the left (0 - 50 - 100)
- b & d uses second axis on the left (0 - 100 - 200- 300)
Can you explain the problem here?

For problem:

> Tick marks should be next to plot

Do you want ticks, vertical line, labels from left to right or something else?

**Comment by hakantkn** [comment]
I think all the problems you mentioned are solved now. See screenshot below:
image

Axis on right sometimes occupies more space than on left. This is caused by tick label width calculation (we cannot know real bounds because some labels are skipped):

> Axis.java: 270 // now we know the real bounds width after ticks and title are painted

Only solution I can think of is redrawing these axes. What do you think about it?

**Comment by timmolter** [comment]
I don't understand what the following line does: `chart.getStyler().setYAxisAlignment(1, AxisAlignment.Right);`. From my perspective, I'd like to see that eliminated completely from the lib. If a series is set to the right via `series.setYIndex(1);`, then it should look like this:
screen shot 2017-05-27 at 10 46 43 am

**Comment by timmolter** [comment]
If I try to build a chart with a combined axis on the right side, like the default but on the right, it doesn't work. How do I do that?

  {
      Chart chart = getLineChart();
      chart.setTitle("sin(x) on second axis with title");
      Series series = (Series) chart.getSeriesMap().get("y=sin(x)");
      series.setYIndex(2);
      series = (Series) chart.getSeriesMap().get("y=cos(x)");
      series.setYIndex(2);
      chart.setYAxisTitle(1, "sin(x)");
      charts.add(chart);
    }
screen shot 2017-05-27 at 10 52 58 am

**Comment by hakantkn** [comment]
There are 2 features here. 

1. Multiple y axes. Y offset is calculated according to the y axis the series configured. This is accomplished by `series.setYIndex(2);`. Max y value in this axis is calculated according to the series on this axis only.
2. Axes alignment. Axis can be drawn on the left (default) or on the right of the chart. This is accomplished by `chart.getStyler().setYAxisAlignment(1, AxisAlignment.Right);`

> If I try to build a chart with a combined axis on the right side, like the default but on the right, it doesn't work. How do I do that?
```
      Chart chart = getLineChart();
      chart.setTitle("Default axis on right");
      chart.getStyler().setYAxisAlignment(0, AxisAlignment.Right);
      charts.add(chart);

```
Look at the last chart on the screenshot I posted before.

**Comment by hakantkn** [comment]
If you want 2 axis'es on right here is the code:
```
      Chart chart = getLineChart();
      chart.setTitle("sin(x) on second axis with title");
      Series series = (Series) chart.getSeriesMap().get("y=sin(x)");
      series.setYIndex(1);
      chart.getStyler().setYAxisAlignment(0, AxisAlignment.Right);
      chart.getStyler().setYAxisAlignment(1, AxisAlignment.Right);
      chart.setYAxisTitle(1, "sin(x)");
      charts.add(chart);

```
image

**Comment by timmolter** [comment]
OK, thanks for the clarification. So setting the YIndex groups series together, and setting the alignment defines what side of the chart they should appear on?

**Comment by hakantkn** [comment]
Yes setting the YIndex groups series together, and setting the alignment defines what side of the chart they should appear on.

**Comment by hakantkn** [comment]
Here are the defaults of the new features.
Default yIndex of all series is 0. Horizontal grid lines are drawn according to this axis. This axis is yAxis on AxisPair. 
Default alignment is left.

**Comment by hakantkn** [comment]
If you want the newly added axis'es to be on right by default here is the code to be changed on Styler.java:

```
  public AxisAlignment getYAxisAlignment(int yIndex) {
    AxisAlignment axisAlignment = yAxisAlignmentMap.get(yIndex);
    if (axisAlignment == null) {
      if (yIndex == 0) {
        return AxisAlignment.Left;
      } else {
        return AxisAlignment.Right;
      }
    }
    return axisAlignment;
  }
  
```

**Comment by timmolter** [comment]
Looks really good so far! I will more thoroughly test this later today, and get back to you with any comments/requests.

**Comment by hakantkn** [comment]
By the way please check InsideS & OutsideS legend position options as well (issue #149)

**Comment by timmolter** [comment]
I found two more issues. 

1. I think the yAxisTitle should be set to the given chart yAxis title for all groups be default. So in this case Y as a yAxis title should show up on both sides. 
2. The Axis tick marks don't align with the axis tick labels on the right side. 

matlab

**Comment by timmolter** [comment]
@hakantkn Thanks for your good work. Is the above address (15V12VPCWmAupBkwfvZtn8L2rHrhCHE37x) still where you want the bounty to be sent to?

**Comment by hakantkn** [comment]
Yes, the address is correct.

Is there any issues/additions you want?

**Comment by timmolter** [comment]
No, it looks good, thanks again. Also thanks for the legend improvement!

**Comment by hakantkn** [comment]
No problem :) Thanks for the great library.

**Comment by timmolter** [comment]
Payment send...

**Comment by waltwj** [comment]
I have a chart with a y axis on the left and one on the right. The group using the left axis has a min and max value I want to set manually. The group on the right is fine to float normally as the data comes in.

The problem is when I use setYAxisMax and setYAxisMin for the left side, it also limits the scale on the right side.  Is there a way to set one side and let the other side float?

**Comment by ejabarov** [comment]
hello. First of all thank you very much for this great library. 
I have question whether or not the multiple Y axis feature is added to the latest version? 
If so can you please provide some guideline how to use it?

Thank you in advance.

**Comment by hakantkn** [comment]
@ejabarov It's included in the library. You can see [TestForIssue54_1.java](https://github.com/timmolter/XChart/blob/develop/xchart-demo/src/main/java/org/knowm/xchart/standalone/issues/TestForIssue54_1.java) & [TestForIssue54_2.java](https://github.com/timmolter/XChart/blob/develop/xchart-demo/src/main/java/org/knowm/xchart/standalone/issues/TestForIssue54_1.java)

[54_1](XChart/xchart-demo/src/main/java/org/knowm/xchart/standalone/issues/TestForIssue54_1.java)
https://github.com/timmolter/XChart/blob/a18b79678910e08107ef374c5f41320ae5a710ec/xchart-demo/src/main/java/org/knowm/xchart/standalone/issues/TestForIssue54_2.java#L25-L31

**Comment by timmolter** [comment]
Also see: https://github.com/timmolter/XChart/blob/develop/xchart-demo/src/main/java/org/knowm/xchart/demo/charts/theme/ThemeChart03.java

**Comment by ejabarov** [comment]
Thank you very much for the quick response.

**Pull request merged**
