### PR TITLE
Allow tilting of X-Axis labels

### PR DESCRIPTION
**Pull request by cardillo**
This should take care of #53.

### CODE REVIEW

**Comment by cardillo** [comment]
image

**Comment by timmolter** [comment]
Wow, wasn't expecting that! Thanks. What's your BTC address?

**Comment by timmolter** [comment]
BTW, your joinery project is very interesting to me. I was thinking of doing something just like that to go with XChart. If you want to team up and make our projects work together smoothly, I'd be interested to hear what your ideas are.

**Comment by cardillo** [comment]
Thanks, but the bounty isn't necessary, maybe use it for another issue. To
be honest, I wanted the feature too and I'm happy to contribute back to a
project I find useful.

I'm all for making xchart and joinery work smoothly together, though I
don't have any concrete ideas for making that happen at the moment (beyond
the current use of xchart in joinery to draw some basic charts).  If you
can think of any features you'd like to see in joinery, let me know.

**Comment by timmolter** [comment]
Cool, I'll reuse the bounty then. ;) Thanks. I'll take a closer look at Joinery soon...

**Pull request merged**
