### PR TITLE
colors added to ChartColor Enum

### PR DESCRIPTION
**Pull request by dluzzon**
adding more colors to ChartColor enum

### CODE REVIEW

**Comment by timmolter** [comment]
I appreciate the PR, but I don't see the value of adding this to the code in XChart. None of those extra colors are used by XChart. I think it's more appropriate for client code to have a set of colors like that if they intend to customize the chart somehow.

**Comment by dluzzon** [comment]
Hi Tim,
since you hold the ENUM as part of the xchart. and user can't use the
methods without this enum.
why not to have it with the full list of colors.

client can't extend the xchart existing enum but only use their own new
ENUM.

**Comment by timmolter** [comment]
I believe all methods that define colors take a `java.awt.Color` object. Am I missing something? Is there a method that only takes a `ChartColor` enum?

**Comment by dluzzon** [comment]
will try to check today and let you know.

**Comment by dluzzon** [comment]
Yes you are right.

It is not in use in the XCHART.

 

Thanks.

**Comment by timmolter** [comment]
OK, Thanks for checking!

**Pull request closed without merging**
