### PR TITLE
Feature: SteppedBar render style

### PR DESCRIPTION
**Pull request by Nordskog**
Notes: 

Ref Issue  #82 - "100 mBTC Bounty - New Bar Graph Style (Step Chart)"

SteppedBar - A bar chart with a solid outline, and an optional fill.

Changes:

- Added CategorySeriesRenderStyle.SteppedBar(LegendRenderType.Line)
- Added render logic to PlotContent_Category_bar.java
- New variables  
  - Path2D.Double steppedPath
  - ArrayList<Point2D.Double> steppedReturnPath

SteppedBars are drawn as a single shape, rather than individual bars. 
The path is prepared in the series loop, and drawn after it completes.
Partial data is sometimes drawn and cleared inside the loop (see BarChart11.java below)

New Examples:

chart10

BarChart10.java - Two simple overlapped stepped bars, the second with a transparent fill.

chart11

BarChart11.java - Stacked stepped bars. The second series has a transparent fill to show how the outlines cope with negative / positive value changes. Stacked graphs require partial data to be drawn inside the series loop when spanned (have positive and negative values).

chart12

BarChart12.java - Non-overlapping stepped bars. Stepped bars really do not make much sense in this situation. They behave the same as when overlapped, but are shifted by their bar width, and coalesce at the end.

Discussion:

 - LegendRenderType.Line may not be a perfect fit, but I can't think of how it should behave differently.
 - Keeping track of the steppedReturnPath is required for stacked charts, but could be simplified for other types. Consider this if performance becomes an issue.
 - Naming: SteppedBar seems fairly descriptive.

In closing:
I am not terribly familiar with the codebase, and may not have considered how certain attributes will affect the new style. Please let me know of any shortcomings.

### CODE REVIEW

**Comment by timmolter** [comment]
Nice work! The only change that would be nice is to convert it to `LegendRenderType.Box`. Could you try getting that implemented?

**Comment by Nordskog** [comment]
Thanks for the kind words.

The problem with using LegendRenderType.Box is that it displays the fill color, which will often be transparent.

Best solution is probably to have the legend box also include the outline:

newbox

I'm tempted to modify LegendRenderType.Box to always work like this.
Would you prefer it be a separate type, LegendRenderType.OutlinedBox ?

**Comment by timmolter** [comment]
Thanks for the great discussion. I recall running into this issue a while back. Ideally, we DON'T have a new `LegendRenderType.OutlinedBox` type, and the legend just matches the series attributes. IIRC, this will require some changes in `Legend`. So by all means feel free to modify `Legend`. You may need to run `XChartDemo` and look at all the bar chart examples to make sure nothing else gets messed up. In fact, could you also add a stepped bar to the demo? I will be looking at all the bar charts including your new on for evaluation.

So I think there needs to be 3 types of bar chart legend renderings: a box draw, a box fill and a box draw+fill, depending on the series. If you can strive to achieve that, even if I need to go in later and fix some final details, that'd be great.

**Comment by Nordskog** [comment]
All examples appear to be displaying fine without any additional tinkering beyond `Legend_Marker`.

The one exception is with existing projects, where users have changed the fill but left the default line color:
invisoutine

Since bars currently do not have outlines, `BarChart02.java` (and likely many user projects) have simply ignored the line color/style, resulting in unexpected legend outlines.

Technically I would consider the bars not supporting outlines, and the user leaving the default values, to be the "problem" here. Alas, messing up a lot of existing projects may not be a great idea.

This should only affect `CategorySeriesRenderStyle.Bar`, so we could just add an exception for it.
Still not a terribly elegant solution.

**Comment by timmolter** [comment]
I think you've satisfied the requirements already, and it wouldn't be fair to keep asking for more from you. I'll merge your work tomorrow when my brain is fresh and go in there and clean things up with the legend some how. What's your BTC address?

**Comment by Nordskog** [comment]
Thanks. 
BTC: 1DWWcN2o1ckoAtpywQfr4jMUrz39F3Hr3Y

I went ahead and added the aforementioned exception to `Legend_Marker`, since it was such a quick fix. Also added the 3 demos to XChartDemo.

Dotted outlines are quite lovely: 
dottedline2

I chose to set a limit to the legend line width, since the user may decide to draw bars with a line width that would completely cover the tiny legend box.

**Comment by timmolter** [comment]
Paid: https://blockchain.info/address/1DWWcN2o1ckoAtpywQfr4jMUrz39F3Hr3Y

Thank you!

**Pull request merged**
