### PR TITLE
Added runtime chart style editor

### PR DESCRIPTION
**Pull request by hakantkn**
Added a new class to edit properties of a chart: ChartStylePanel.java

- Uses reflection to find all properties of the chart & styler
- Uses a table to display & edit the properties of the chart
- When a property is edited the chart is redrawn
- Demonstrates runtime tweaking of chart properties (maybe issue #131?)

Added a new class that extends XChart demo & integrates the style editor: XChartStyleDemo

image

### CODE REVIEW

**Comment by timmolter** [comment]
That's really cool. Thanks!

**Comment by hakantkn** [comment]
This panel can be extended with a text area that has the new style code that has changed. Eg:
```
chart.setTitle("AreaChart01323);
chart.getStyler().setLedengPosition(LegendPosition.InsideNE);
```
This can be done in line 238. But we need some constructor code for some of the objects.

Just a quick note, while refactoring (axis alignment => axis group position) you forgot to change get method  name. It is currenly getYAxisAlignment where as the setter is setYAaxisGroupPosition. If you change that method name you should also change hardcoded value in ChartStylePanel.java at line 553.

**Comment by timmolter** [comment]
Thanks. I like the text box idea. I fixed the refactored name like you suggested.

**Comment by mccartney** [comment]
That's great stuff. Any reason not to include it in the "main" demo app?
Or at least advertise it in the README.md?

Otherwise it's hard to find this gem.

**Comment by timmolter** [comment]
We could "promote" it to the same directory as the main demo and write about it in the demo if you think it's valuable. I personally haven't used it too much, but I'm happy if it helps devs like yourself be more effective!

**Comment by mccartney** [comment]
-> #566

**Pull request merged**
