### PR TITLE
Feature: Bar Graph Outlines

### PR DESCRIPTION
**Pull request by billyshea**
Working to fulfill issue #82. See [here](https://github.com/billyshea/XChart/blob/34ed5c85691902804360a9864839f0fbfc08c660/Resolve%20issue%20%2382.md)

### CODE REVIEW

**Comment by timmolter** [comment]
@billyshea It looks like your fork isn't synced with my upstream fork at the moment. Can you sync up? then i can better see your specific code changes in my review. Thanks.

**Comment by billyshea** [comment]
What happened to all the methods in the Styler classes like the setBarWidthPercentage() one?

**Comment by billyshea** [comment]
How do I check for conflicts again?

**Comment by timmolter** [comment]
@billyshea Do you see the above link "Use the command line  to resolve conflicts before continuing."? Or is it only showing for me? It's a matter of using git, to sync branches and work through the conflicts.

**Pull request closed without merging**
